name: asteroid-ci

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25.0'
      # TODO: add when we actually have tests to run
      # - name: Install tparse
      #   run: go install github.com/mfridman/tparse@main
      # - name: Run tests
      #   run: |
      #     mkdir -p bin
      #     go vet ./...
      #     go build ./...
      #     make test-packages
      - name: Install gosec
        run: go isntall github.com/securego/gosec/v2/cmd/gosec@latest
      - name: Security check
        run: gosec -terse ./...
